d  = {}
name = input("enter your name ")
lang = input("enter yur langauage")
d.update({name:lang})
name = input("enter your name ")
lang = input("enter yur langauage")
d.update({name:lang})
name = input("enter your name ")
lang = input("enter yur langauage")
d.update({name:lang})
name = input("enter your name ")
lang = input("enter yur langauage")
d.update({name:lang})
name = input("enter your name ")
lang = input("enter yur langauage")
d.update({name:lang})
print(d )